#ifndef INCLUDES_SPES_ENGINE_CORE_APPLICATION_H
#define INCLUDES_SPES_ENGINE_CORE_APPLICATION_H

enum APP_EXIT_CODE {
	EXIT_SUCCESS = 0,
	FAILURE,
	CRITICAL
};

enum APP_EXIT_CODE start_app();


#endif//INCLUDES_SPES_ENGINE_CORE_APPLICATION_H